[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "nextjs"
  targetPort = 3000

[functions]
  directory = "netlify/functions"

[context.production.environment]
  HUGGINGFACE_API_KEY = "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"

